/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { TradeData, TradeDataInterface } from "../TradeData";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "itemCountTraded",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "volumeTraded",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class TradeData__factory {
  static readonly abi = _abi;
  static createInterface(): TradeDataInterface {
    return new utils.Interface(_abi) as TradeDataInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TradeData {
    return new Contract(address, _abi, signerOrProvider) as TradeData;
  }
}
