/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface TradeDataInterface extends ethers.utils.Interface {
  functions: {
    "itemCountTraded(address)": FunctionFragment;
    "volumeTraded(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "itemCountTraded",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "volumeTraded",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "itemCountTraded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "volumeTraded",
    data: BytesLike
  ): Result;

  events: {};
}

export class TradeData extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TradeDataInterface;

  functions: {
    itemCountTraded(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    volumeTraded(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  itemCountTraded(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  volumeTraded(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    itemCountTraded(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    volumeTraded(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    itemCountTraded(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    volumeTraded(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    itemCountTraded(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    volumeTraded(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
